"""add new

Revision ID: 493871941678
Revises: 
Create Date: 2016-11-16 15:29:49.855955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493871941678'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=11), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('avatar_picture', sa.String(length=120), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_email'), 'client', ['email'], unique=True)
    op.create_index(op.f('ix_client_phone_number'), 'client', ['phone_number'], unique=True)
    op.create_index(op.f('ix_client_register_time'), 'client', ['register_time'], unique=False)
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('campus', sa.String(length=10), nullable=False),
    sa.Column('avatar_picture', sa.String(length=120), nullable=True),
    sa.Column('register_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_campus'), 'server', ['campus'], unique=False)
    op.create_index(op.f('ix_server_email'), 'server', ['email'], unique=True)
    op.create_index(op.f('ix_server_register_time'), 'server', ['register_time'], unique=False)
    op.create_index(op.f('ix_server_username'), 'server', ['username'], unique=True)
    op.create_table('form',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_time', sa.DateTime(), nullable=True),
    sa.Column('campus', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('machine_model', sa.String(length=64), nullable=False),
    sa.Column('OS', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=240), nullable=False),
    sa.Column('picture_content', sa.String(length=900), nullable=True),
    sa.Column('handle_server_id', sa.Integer(), nullable=True),
    sa.Column('post_client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['handle_server_id'], ['server.id'], ),
    sa.ForeignKeyConstraint(['post_client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_campus'), 'form', ['campus'], unique=False)
    op.create_index(op.f('ix_form_status'), 'form', ['status'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_status'), table_name='form')
    op.drop_index(op.f('ix_form_campus'), table_name='form')
    op.drop_table('form')
    op.drop_index(op.f('ix_server_username'), table_name='server')
    op.drop_index(op.f('ix_server_register_time'), table_name='server')
    op.drop_index(op.f('ix_server_email'), table_name='server')
    op.drop_index(op.f('ix_server_campus'), table_name='server')
    op.drop_table('server')
    op.drop_index(op.f('ix_client_register_time'), table_name='client')
    op.drop_index(op.f('ix_client_phone_number'), table_name='client')
    op.drop_index(op.f('ix_client_email'), table_name='client')
    op.drop_table('client')
    ### end Alembic commands ###
